language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm run coverage
  - npm run build
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"