sudo: required
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "$HOME/.npm"
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
install:
  - npm ci
script:
  - npm run coveralls
  - npm run build
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
